language: r

cache: packages

sudo: false

r:
  - bioc-devel
  - bioc-release

bioc_packages:
  - BiocStyle
  - testthat
  - DESeq2
  - limma

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
